[package]
name = "smart_contract"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy.workspace = true
url.workspace = true
async-trait.workspace = true
derive_more.workspace = true
thiserror.workspace = true
log = "0.4.27"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
