[workspace]
members = [
    "prover",
    "rln_proof"
, "smart_contract"]
resolver = "2"

[workspace.dependencies]
ark-bn254 = { version = "0.5", features = ["std"] }
ark-serialize = "0.5"
ark-groth16 = "0.5"
url = "2.5.4"
alloy = { version = "1.0", features = ["getrandom", "sol-types", "contract", "provider-ws"] }
async-trait = "0.1"
# dev
criterion = "0.6"


