NATIVE_FLAGS = -C target-cpu=native
RAYON_NUM_THREADS ?= 64
PROOF_SERVICE_COUNT ?= 64
PROOF_COUNT ?= 64

.PHONY: build
build:
	RAYON_NUM_THREADS=$(RAYON_NUM_THREADS) PROOF_SERVICE_COUNT=$(PROOF_SERVICE_COUNT) PROOF_COUNT=$(PROOF_COUNT) RUSTFLAGS="$(NATIVE_FLAGS)" cargo build --release $(ARGS)

.PHONY: bench
bench:
	RAYON_NUM_THREADS=$(RAYON_NUM_THREADS) PROOF_SERVICE_COUNT=$(PROOF_SERVICE_COUNT) PROOF_COUNT=$(PROOF_COUNT) RUSTFLAGS="$(NATIVE_FLAGS)" cargo bench $(ARGS)