NATIVE_FLAGS = -C target-cpu=native

.PHONY: build
build:
	cargo build --release $(ARGS)

RAYON_NUM_THREADS ?= 64
PROOF_SERVICE_COUNT ?= 64
PROOF_COUNT ?= 64

.PHONY: bench
bench:
	RAYON_NUM_THREADS=$(RAYON_NUM_THREADS) PROOF_SERVICE_COUNT=$(PROOF_SERVICE_COUNT) PROOF_COUNT=$(PROOF_COUNT) RUSTFLAGS="$(NATIVE_FLAGS)" cargo bench $(ARGS)

# Example: make bench RAYON_NUM_THREADS=128 PROOF_SERVICE_COUNT=32 PROOF_COUNT=8 ARGS="--bench prover_bench"