[package]
name = "status_rln_prover"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
tonic = { version = "0.13", features = ["gzip"] }
tonic-reflection = "*"
tonic-web = "*"
prost = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
tracing-test = "0.2.5"
alloy.workspace = true
thiserror = "2.0"
futures = "0.3"
rln = { git = "https://github.com/vacp2p/zerokit", default-features = false }
ark-bn254.workspace = true
ark-serialize.workspace = true
dashmap = "6.1.0"
scc = "2.3"
bytesize = "2.0.1"
chrono = "0.4.41"
parking_lot = "0.12"
tower-http = { version = "0.6.4", features = ["cors"] }
http = "*"
async-channel = "2.3.1"
rand = "0.8.5"
derive_more = "2.0.1"
url.workspace = true
num-bigint = "0.4"
async-trait.workspace = true
rln_proof = { path = "../rln_proof" }
smart_contract = { path = "../smart_contract" }

[build-dependencies]
tonic-build = "*"

[dev-dependencies]
criterion.workspace = true
claims = "0.8"
ark-groth16.workspace = true

[[bench]]
name = "user_db_heavy_write"
harness = false
