[package]
name = "rln_proof"
version = "0.1.0"
edition = "2024"

[dependencies]
rln = { git = "https://github.com/vacp2p/zerokit", package = "rln", features = ["default"] }
zerokit_utils = { git = "https://github.com/vacp2p/zerokit", package = "zerokit_utils", features = ["default"] }
ark-bn254 = { version = "0.5", features = ["std"] }
ark-groth16 = "*"
ark-relations = "*"
ark-serialize = "0.5.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "generate_proof"
harness = false
