[package]
name = "rln_proof"
version = "0.1.0"
edition = "2024"

[lib]
bench = false

[dependencies]
rln = { git = "https://github.com/vacp2p/zerokit", package = "rln", features = [
    "pmtree-ft",
] }
zerokit_utils = { git = "https://github.com/vacp2p/zerokit", package = "zerokit_utils", features = [
    "default",
] }
ark-bn254.workspace = true
ark-groth16.workspace = true
ark-serialize.workspace = true
ark-relations = "0.5"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "generate_proof"
harness = false
